decay_steps: 300
starting_epsilon: 1
discount_factor: 0.9999
batch_size: 64
memory_size: 50000
summaries_path: "./tensorflow_summaries/tug_of_war/caml_gvf/mbi_v1/reinforce_summary"
update_frequency: 10
replace_frequency: 1
epsilon_timesteps: 20000
starting_epsilon: 1
final_epsilon: 0.02
is_random_agent_1: False
is_random_agent_2: False
collecting_experience: False
use_prior_memory: False
# 0 is no collecting, other number will be the number of collected episodes
is_collecting_GVF_seq: 1000
exp_save_path: 'abp/examples/pysc2/tug_of_war/caml_collected_datasets/caml_gvf_dataset.pt' 
agents_name: 
    - "marine"
    - "baneling"
    - "immortal"
    
features_list: 
    - "self_create_building" # 7 len
#     - "self_unit_spawn" # 6 len
    - "reward_vector" # 4 len
    - "self_damage_to_nexus" # 6 len
    - "self_get_damage_nexus" # 6 len
    