layers:
  - type: "FCwithBN"
    neurons: 1024
    size: 1024

  - type: "FCwithBN"
    neurons: 512
    size: 512
    
input_shape:
    - 68

output_shape: 4

shared_layers: []
aggregator: "average"

network_path: "./saved_models/tug_of_war/trans/health/v2_grid_all.ckpt"
summaries_path: "./tensorflow_summaries/tug_of_war/trans/health/v2_grid_all/network_summary"
summaries_step: 1000000000
restore_network: False
learning_rate: 0.00005
save_steps: 1000000000
save_network: True
