layers:
  - type: "FC"
    neurons: 1024

  - type: "FC"
    neurons: 512

  - type: "FC"
    neurons: 256
input_shape:
    - 32

output_shape: 4

shared_layers: []
aggregator: "average"

network_path: "./saved_models/tug_of_war/trans/health/v1.ckpt"
summaries_path: "./tensorflow_summaries/tug_of_war/trans/health/v1/network_summary"
summaries_step: 1000
restore_network: False
learning_rate: 0.00005
save_steps: 1000
save_network: True
