name: "four towers friendly units group dereward random HP"
env: "four_towers_friendly_units_group_dereward random HP-v1"
summaries_path: "./tensorflow_summaries/four_towers_friendly_units_group_dereward/hra/randomHP/evaluation_summary"
test_episodes: 10
training_episodes: 100
render: True
sleep: 5
